version: "3.6"

services:
  vaultwarden:
    image: vaultwarden/server:latest # with amd64 and armv7 you can use alpine
    restart: unless-stopped
    environment:
      DOMAIN: https://bw.${DOMAIN_NAME}
    env_file: 
      - .env
    volumes:
      - "./data/bw:/data"
  caddy:
    build:
      context: ./caddy
      args:
        - VUE_APP_DOMAIN_NAME=www.d34d.fun
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./data/caddy:/data"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL: ${EMAIL}
  dnscryptProxy:
    image: gists/dnscrypt-proxy
    networks:
      default:
        ipv4_address: 10.69.0.101
    volumes:
      - "./dnscrypt-proxy/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
      - "./dnscrypt-proxy/blocked-names.txt:/etc/dnscrypt-proxy/blocked-names.txt:ro"
    restart: unless-stopped    
  bind:
    build: ./bind9
    networks:
      default:
        ipv4_address: 10.69.0.102
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped    
  openvpn:
    build: ./openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - "./data/openvpn:/data"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped    
  doh:
    image: satishweb/doh-server
    environment:
      UPSTREAM_DNS_SERVER: udp:bind:53
      DOH_HTTP_PREFIX: /dns-query
    restart: unless-stopped    
  dot:
    build: ./stunnel
    volumes:
      - "${CERTS_PATH}.key:/etc/stunnel/stunnel.key:ro"
      - "${CERTS_PATH}.crt:/etc/stunnel/stunnel.pem:ro"
    ports:
      - "853:853"
    environment:
      STUNNEL_SERVICE: dot
      STUNNEL_ACCEPT: 853
      STUNNEL_CONNECT: bind:53
    restart: unless-stopped    
  postfix:
    build: ./mail/postfix
    volumes:
      - "${CERTS_PATH}.key:/certs/server.key:ro"
      - "${CERTS_PATH}.crt:/certs/server.crt:ro"
    ports:
      - "25:25"
      - "587:587"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PUBLIC_IP: ${PUBLIC_IP}
    restart: unless-stopped    

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.69.0.0/24
