version: "3.6"

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    restart: unless-stopped
    environment:
      - DOMAIN=https://bw.${DOMAIN_NAME}
    volumes:
      - "./data/bw:/data"
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./data/caddy:/data"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL=${EMAIL}
  dnscryptProxy:
    image: gists/dnscrypt-proxy
    volumes:
      - "./dnscrypt-proxy/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro"
      - "./dnscrypt-proxy/blocked-names.txt:/etc/dnscrypt-proxy/blocked-names.txt:ro"
    restart: unless-stopped    

volumes:
  bw_data:
  caddy_data:
